---

#################################################
# General parameters                            #
#################################################

# Location where configuration files will be stored
config_dir: '~/homelab-dns'

#################################################
# BIND9 DNS server options                      #
#################################################

# Subnets that are allowed to use the resolver
# comma separated list of IP addresses, IP addresses with CIDR mask, or address match list names "none", "any", "localhost", and "localnets"
allowed_clients: "192.168.1.0/24,127.0.0.1"

# DNS entries for the bind9 server in your private zone
# These will be translated into A and PTR records
dns_zone: "home.example.com"
hosts:
  - name: "server1" # will resolve "server1.home.example.com" to 192.168.1.11
    addr: "192.168.1.11"
  - name: "server2"
    addr: "192.168.1.12"
  - name: "*.server2" # wildcard will resolve all subdomains of "server2.home.example.com" to 192.168.1.12
    addr: "192.168.1.12"

# (optional) Additional A records outside of your private zone
additional_a_records:
  - somewhere.else.net=0.0.0.0

# (optional) CNAME records
cname_records:
  - some.external.domain=internal.home.example.com

#################################################
# Configure webinterfaces                       #
#################################################

# Activate webinterfaces
# Setting this to false will cause the code to ignore everything else in this section.
activate_webinterfaces: true

# Activate the traefik API and Dashboard (on 'traefik'-subdomain, e.g. traefik.ns.home.example.com)
activate_traefik_dashboard: true
