---
- name: Configure Homelab DNS.
  hosts: homelab_dns

  pre_tasks:
    - name: Load configuration.
      ansible.builtin.include_vars: config.yml

    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

  tasks:
    - name: Install Docker if not available
      ansible.builtin.import_tasks: tasks/docker-setup.yml

    - name: Create config directories if they do not exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ config_dir }}"
        - "{{ config_dir }}/record-service"
        - "{{ config_dir }}/record-service/www"
        - "{{ config_dir }}/record-service/config"

    - name: Copy templated config files into place
      ansible.builtin.template:
        src: templates/{{ item.src }}
        dest: "{{ config_dir }}/{{ item.dest }}"
      loop:
        - src: docker-compose.yml.j2
          dest: docker-compose.yml
        - src: record-service/www/index.html.j2
          dest: record-service/www/index.html
        - src: record-service/www/api.json.j2
          dest: record-service/www/api.json
        - src: record-service/www/api.yaml.j2
          dest: record-service/www/api.yaml
        - src: record-service/config/yaml-mime-type.conf.j2
          dest: record-service/config/yaml-mime-type.conf

    - name: Ensure homelab-dns configuration is running
      ansible.builtin.command:
        cmd: docker compose up --detach
        chdir: "{{ config_dir }}"
      register: docker_compose

    - name: docker compose output
      ansible.builtin.debug:
        msg: "{{ docker_compose['stderr_lines'] }}"
